[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
startCommand = "npm start"
watchPatterns = ["frontend/**/*"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[source]
directory = "frontend"